apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonLabels:
  app: snack
configMapGenerator:
- name: snack
  env: snack.env
secretGenerator:
- name: snack
  env: secrets/snack.env
