apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
bases:
- ../base
patchesStrategicMerge:
- ingress-spec.yaml
configMapGenerator:
- name: snack
  behavior: merge
  env: snack.env
